ローカルでDcokerコンテナを立ち上げたときにredocly側がエラーで動かなかったのを修正する
GiganticMinecraft/seichi-portal-api-schema pull request #166
Opened 2024-09-08 02:03 UTC by Lucky3028

2024-09-08 02:33 UTC, rito528 requested changes
> コンテナ起動時にtspのコンパイルとredoclyのドキュメント生成がこけていた

ここでこけたことが今までなかったんですが、どういう挙動をしていたのかもう少し詳細が欲しいです

> tspのコンパイルはcompile-and-up-compose.shでしていて、Dockerコンテナはコンパイルして生成されたopenapi,yamlをボリュームでマウントしているので、Dockerコンテナの中でtspのコンパイルはしなくてよい

これは確かにそうですが、Docker コンテナとシェルスクリプトのどちらか1つでコンパイルすることを前提にするならば、シェルスクリプトでコンパイルすることを前提にするよりも、Docker コンテナ内でコンパイルすることを前提にしたほうが良いかなと思いました。

2024-09-08 02:57 UTC, Lucky3028 commented
あとでかきます

2024-09-08 03:52 UTC, Lucky3028 commented
https://github.com/GiganticMinecraft/seichi-portal-api-schema/blob/322c362c5ae38938e09be1971c5b9ef92b539ee5/compose.yaml#L19-L20

redocly のコンテナに対してマウントしているボリュームは、`./tsp-output/@typespec/openapi3`を`/schema`にマウントするものだけなので、`/tmp/files/src`がなく、tspのコンパイルは失敗します。
よって、そのコンパイルの結果出力先である`tsp-output/@typespec/openapi3/openapi.yaml`は存在しないので、redoclyのドキュメント生成も失敗します。

以下ログです。
```zsh
❯ docker container ls
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS         PORTS
                     NAMES
c3b79515b57d   seichi-portal-api-schema-redocly   "./entrypoint.sh"        5 seconds ago   Up 4 seconds   127.0.0.1:8082->8080/tcp           redocly
90c249178056   swaggerapi/swagger-ui              "/docker-entrypoint.…"   5 seconds ago   Up 4 seconds   80/tcp, 127.0.0.1:8081->8080/tcp   swagger-ui
❯ docker logs c3b79515b57d
TypeSpec compiler v0.59.1

error file-not-found: File /tmp/files/src not found.

tsp-output/@typespec/openapi3/openapi.yaml does not exist or is invalid.

Please provide a valid path.

Starting up http-server, serving ./docs

http-server version: 14.1.1

http-server settings:
CORS: disabled
Cache: 3600 seconds
Connection Timeout: 120 seconds
Directory Listings: visible
AutoIndex: visible
Serve GZIP Files: false
Serve Brotli Files: false
Default File Extension: none

Available on:
  http://127.0.0.1:8080
  http://172.18.0.2:8080
Hit CTRL-C to stop the server
❯
```

2024-09-08 03:58 UTC, Lucky3028 commented
> これは確かにそうですが、Docker コンテナとシェルスクリプトのどちらか1つでコンパイルすることを前提にするならば、シェルスクリプトでコンパイルすることを前提にするよりも、Docker コンテナ内でコンパイルすることを前提にしたほうが良いかなと思いました。

はそうですね

2024-09-08 03:58 UTC, Lucky3028 commented
↑の件の共有認識が取れたらそちらに書き換えます

2024-09-08 09:50 UTC, rito528 commented
> @rito528
> 
> https://github.com/GiganticMinecraft/seichi-portal-api-schema/blob/322c362c5ae38938e09be1971c5b9ef92b539ee5/compose.yaml#L19-L20
> 
> redocly のコンテナに対してマウントしているボリュームは、`./tsp-output/@typespec/openapi3`を`/schema`にマウントするものだけなので、`/tmp/files/src`がなく、tspのコンパイルは失敗します。 よって、そのコンパイルの結果出力先である`tsp-output/@typespec/openapi3/openapi.yaml`は存在しないので、redoclyのドキュメント生成も失敗します。
> 
> 以下ログです。
> 
> ```shell
> ❯ docker container ls
> CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS         PORTS
>                      NAMES
> c3b79515b57d   seichi-portal-api-schema-redocly   "./entrypoint.sh"        5 seconds ago   Up 4 seconds   127.0.0.1:8082->8080/tcp           redocly
> 90c249178056   swaggerapi/swagger-ui              "/docker-entrypoint.…"   5 seconds ago   Up 4 seconds   80/tcp, 127.0.0.1:8081->8080/tcp   swagger-ui
> ❯ docker logs c3b79515b57d
> TypeSpec compiler v0.59.1
> 
> error file-not-found: File /tmp/files/src not found.
> 
> tsp-output/@typespec/openapi3/openapi.yaml does not exist or is invalid.
> 
> Please provide a valid path.
> 
> Starting up http-server, serving ./docs
> 
> http-server version: 14.1.1
> 
> http-server settings:
> CORS: disabled
> Cache: 3600 seconds
> Connection Timeout: 120 seconds
> Directory Listings: visible
> AutoIndex: visible
> Serve GZIP Files: false
> Serve Brotli Files: false
> Default File Extension: none
> 
> Available on:
>   http://127.0.0.1:8080
>   http://172.18.0.2:8080
> Hit CTRL-C to stop the server
> ❯
> ```

これを試したんですが、スクリプトから実行した TypeSpec のコンパイルに失敗した結果、`openapi.yaml` が生成されなかったために redocly の起動に失敗しているようですね....(ローカルで作成した `openapi.yaml` をコピーして redocly が読んでいるので)
なのでコンテナ内ではなく、開発環境で `tsp compile ./src` を実行してコンパイルをしてからだと起動できるようになるはずです。
しかし、せっかく用意してあるスクリプトを実行するだけではコンパイルに失敗してコンテナが起動できないのは問題なので、何とかしたほうがよさそう....

2024-09-08 10:08 UTC, Lucky3028 commented
> ローカルで作成した openapi.yaml をコピーして redocly が読んでいるので

ってどこでやってます？

2024-09-08 10:21 UTC, rito528 commented
https://github.com/GiganticMinecraft/seichi-portal-api-schema/blob/322c362c5ae38938e09be1971c5b9ef92b539ee5/compose.yaml#L19-L22

ここです

2024-09-08 10:42 UTC, Lucky3028 commented
ありがとうございます。
`/schema` にマウントしたものって読まれてないのでは？

https://github.com/GiganticMinecraft/seichi-portal-api-schema/blob/322c362c5ae38938e09be1971c5b9ef92b539ee5/docker/entrypoint.sh#L5

2024-09-08 15:09 UTC, rito528 commented
私の環境で起動したときのログでは、ローカルでコンパイルしたあとに `docker compose up -d` をすると読み込まれているようですね...

```
2024-09-08 18:44:35 
2024-09-08 18:44:35   🔎  Preview server running at http://0.0.0.0:8080
2024-09-08 18:44:35 
2024-09-08 18:44:35   👀  Watching /schema/openapi.yaml and all related resources for changes
2024-09-08 18:44:35 
2024-09-08 18:44:35 
2024-09-08 18:44:35 Bundling...
2024-09-08 18:44:35 
2024-09-08 18:44:35 Created a bundle for /schema/openapi.yaml successfully
2024-09-08 18:44:35 Using Redoc community edition.
2024-09-08 18:44:35 Login with redocly login or use an enterprise license key to preview with the premium docs.
2024-09-08 18:44:35 
```

2024-09-10 16:49 UTC, Lucky3028 commented
謎挙動かも。
一回吹っ飛ばしてもう一度mainのもの引っ張ってきてやってみてくれませんか？
@rito528

2024-09-14 06:23 UTC, rito528 commented
> 謎挙動かも。 一回吹っ飛ばしてもう一度mainのもの引っ張ってきてやってみてくれませんか？ @rito528

`main` を新しくリモートから持ってきて試しても、以下のようにログがでて普通に起動できますね。
```
2024-09-14 15:21:54 
2024-09-14 15:21:54   🔎  Preview server running at http://0.0.0.0:8080
2024-09-14 15:21:54 
2024-09-14 15:21:54   👀  Watching /schema/openapi.yaml and all related resources for changes
2024-09-14 15:21:54 
2024-09-14 15:21:54 Using Redoc community edition.
2024-09-14 15:21:54 Login with redocly login or use an enterprise license key to preview with the premium docs.
2024-09-14 15:21:54 
2024-09-14 15:21:54 
2024-09-14 15:21:54 Bundling...
2024-09-14 15:21:54 
2024-09-14 15:21:54 Created a bundle for /schema/openapi.yaml successfully
```

2024-09-14 16:08 UTC, Lucky3028 commented
ありがとうございます。どうしてそこで差異が出るんだ...？？？

2024-09-14 16:28 UTC, Lucky3028 commented
めんどくさいので

> これは確かにそうですが、Docker コンテナとシェルスクリプトのどちらか1つでコンパイルすることを前提にするならば、シェルスクリプトでコンパイルすることを前提にするよりも、Docker コンテナ内でコンパイルすることを前提にしたほうが良いかなと思いました。

を別PRでやっちゃいます

2024-09-14 16:28 UTC, closed without merging

2024-09-14 16:32 UTC, rito528 commented
ただ、なんで Lucky さんの環境でこのような挙動をするのかは気になりますね....