`/forms`APIの定義を見直す
GiganticMinecraft/seichi-portal-api-schema pull request #60
Opened 2023-03-07 18:19 UTC by rito528

現在のAPI定義では、REST APIの思想に反するものになっています。
例えば、今までの定義だと`/forms`に`GET`リクエストには、以下のようにレスポンス内容が異なる物がありました。
- すべてのフィールドを含んだフォーム概要
- 説明文を含んだフォーム概要
- 回答期限が切れたフォーム概要

これらはそれぞれレスポンス内容として分けられるべきではなく、一つのAPIからは一意の内容のレスポンスになるべきです。
このようなAPI実装にする場合は、REST APIではなくGraphQLを使ったほうが良いことになってしまいます(少なくともREST APIでするべき内容ではなくなってしまう)

※今後の方針として
API構造を見直し、フロントエンド側で複数のREST APIを呼んでいくような形にしていきたいです。

2023-03-08 08:01 UTC, Lucky3028 commented
説明文や回答期限はnullableなので当たり前では？ @rito528

2023-03-08 12:31 UTC, rito528 commented
説明分や回答期限がnullableならば、nullだった場合に要素を削除するというよりも、nullならばnullと返す方が良くないですか？

2023-03-09 07:01 UTC, Lucky3028 commented
なるほど？nullが嫌いすぎてその発想がなかった
そうするのであれば賛成です

2023-03-09 07:13 UTC, rito528 commented
👍

2023-03-09 09:05 UTC, Lucky3028 approved these changes

2023-03-09 10:00 UTC, rito528 commented
@Lucky3028 
PRを分割してください。
今回`/forms/{formId}`について触れていないPRなので、変更内容が把握できない&何を見てほしいのかわからないです。

2023-03-09 10:01 UTC, rito528 commented
あと、同じPRに違う変更内容を加えられるとrejectできないので、今後は控えていただけると助かります。
※Changes Requestを出すなり、コメントするなりしてほしいです。

2023-03-09 10:34 UTC, Lucky3028 commented
すみません…

2023-03-09 10:38 UTC, Lucky3028 commented
resetしておきます

2023-03-09 11:44 UTC, Lucky3028 requested changes

2023-03-09 11:44 UTC, Lucky3028 commented on schema/paths/forms/index.yml
> +
```suggestion

```
余計なスペースを消してください。

2023-03-09 11:44 UTC, Lucky3028 commented on schema/paths/forms/index.yml
> +        offsetを1とすると2件目からのデータが取得できます。
```suggestion
        例えば、offsetを1とすると2件目からのデータが取得できます。
```

2023-03-09 11:46 UTC, Lucky3028 requested changes

2023-03-09 11:46 UTC, Lucky3028 commented on schema/paths/forms/index.yml
> +                - description
```suggestion
```
descriptionはnullableです

2023-03-09 11:49 UTC, merged